import { useState, useEffect } from "react";
import { motion } from "framer-motion";
import { Link, useParams, useNavigate } from "react-router-dom";
import { 
  ShieldCheck, 
  ArrowLeft,
  CheckCircle2,
  Lock,
  Loader2,
  MapPin,
  Clock,
  User,
  Activity,
  FileText,
  Download,
  Share2,
  Camera,
  Image as ImageIcon,
  AlertCircle
} from "lucide-react";
import toast from "react-hot-toast";
import { getWorkOrderById, getIssueById, MOCK_CONTRACTORS } from "../services/api";
import { WorkOrder, Issue } from "../types";

export default function AuditTrailPage() {
  const { id } = useParams<{ id: string }>();
  const navigate = useNavigate();
  const [workOrder, setWorkOrder] = useState<WorkOrder | null>(null);
  const [issue, setIssue] = useState<Issue | null>(null);

  useEffect(() => {
    if (id) {
      const wo = getWorkOrderById(id);
      if (wo) {
        setWorkOrder(wo);
        const parentIssue = getIssueById(wo.issueId);
        if (parentIssue) {
          setIssue(parentIssue);
        }
      }
    }
  }, [id]);

  if (!workOrder || !issue) {
    return (
      <div className="min-h-screen bg-[#FAFAFA] flex flex-col items-center justify-center p-6 text-center">
        <div className="w-24 h-24 bg-white rounded-full flex items-center justify-center mb-6 shadow-sm border border-slate-100">
          <AlertCircle size={40} className="text-slate-300" />
        </div>
        <h1 className="text-3xl font-display font-extrabold text-ink mb-3">Audit trail not found</h1>
        <p className="text-slate-500 font-medium max-w-md mx-auto mb-8">
          This case may not exist or has not been created yet.
        </p>
        <button onClick={() => navigate('/dashboard')} className="px-8 py-3 bg-violet-deep text-white rounded-full font-bold shadow-lg shadow-violet/20 hover:bg-violet transition-colors">
          Go to Dashboard
        </button>
      </div>
    );
  }

  const contractor = workOrder.assignedContractor || MOCK_CONTRACTORS[0];
  const isPaymentReleased = workOrder.status === 'Payment Released';
  const isAIVerified = workOrder.status === 'AI Verified' || isPaymentReleased;

  const downloadReport = () => {
    const reportContent = `
CIVICA AUDIT REPORT
===================
Work Order ID: ${workOrder.workOrderId}
Issue ID: ${issue.id}
Title: ${issue.title}
Category: ${issue.category}
Severity: ${issue.severity}
Location: ${issue.location}
Reported By: ${issue.reportedBy}

CONTRACTOR DETAILS
==================
Assigned To: ${contractor.name}
Contractor Score: ${contractor.contractorScore}/5
Quality: ${contractor.tier}

AI VERIFICATION RESULTS
=======================
Repair Confidence: ${workOrder.verificationResult?.repairConfidence || 'N/A'}%
Location Match: ${workOrder.verificationResult?.sameLocationMatch || 'N/A'}%
GPS Verified: ${workOrder.verificationResult?.gpsVerified ? 'Yes' : 'No'}
Timestamp Verified: ${workOrder.verificationResult?.timestampVerified ? 'Yes' : 'No'}
Tamper Risk: ${workOrder.verificationResult?.evidenceTamperRisk || 'N/A'}
Repair Quality: ${workOrder.verificationResult?.repairQuality || 'N/A'}
Issue Resolved: ${workOrder.verificationResult?.issueResolved ? 'Yes' : 'No'}
Recommendation: ${workOrder.verificationResult?.recommendation || 'N/A'}

PAYMENT ASSURANCE
=================
Estimated Cost: ${workOrder.estimatedCost}
Payment Status: ${isPaymentReleased ? 'Released' : 'Pending'}

Generated by Civica Assurance Engine.
    `.trim();

    const blob = new Blob([reportContent], { type: "text/plain;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = `civica-audit-report-${workOrder.workOrderId}.txt`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
    toast.success("Audit report downloaded.");
  };

  const copyCaseLink = () => {
    navigator.clipboard.writeText(window.location.href);
    toast.success("Case audit link copied.");
  };

  // Helper to determine step status
  const getStepStatus = (stepIndex: number) => {
    const statuses = [
      'Reported',
      'AI Reviewed',
      'Work Order Created',
      'Contractor Assigned',
      'Repair Uploaded',
      'AI Verified',
      'Payment Recommended',
      'Payment Released'
    ];
    const currentIndex = statuses.indexOf(workOrder.status === 'Rework Required' ? 'Repair Uploaded' : workOrder.status);
    
    // For Payment Recommended logic
    let effectiveIndex = currentIndex;
    if (workOrder.status === 'AI Verified' && workOrder.verificationResult?.recommendation === 'Release Payment') {
      effectiveIndex = 6;
    }
    if (workOrder.status === 'Payment Released') {
      effectiveIndex = 7;
    }

    if (stepIndex < effectiveIndex) return 'completed';
    if (stepIndex === effectiveIndex) return 'current';
    return 'pending';
  };

  const timelineSteps = [
    {
      title: "Issue Reported",
      desc: `Citizen submitted issue evidence for ${issue.title}.`,
      actor: "Citizen App",
      time: issue.createdAt,
      badge: "Reported",
      index: 0
    },
    {
      title: "AI Issue DNA Generated",
      desc: "Civica AI classified the issue, scored severity, checked duplicate risk, and recommended SLA.",
      actor: "Civica AI",
      time: "Shortly after",
      badge: "AI Reviewed",
      index: 1
    },
    {
      title: "Work Order Created",
      desc: `Work order ${workOrder.workOrderId} was generated from the AI-reviewed civic case.`,
      actor: "Municipal Admin",
      time: "Same day",
      badge: "Work Order Created",
      index: 2
    },
    {
      title: "Contractor Assigned",
      desc: `${contractor.name} was assigned based on contractor score and SLA performance.`,
      actor: "Municipal Admin",
      time: "Same day",
      badge: "Contractor Assigned",
      index: 3
    },
    {
      title: "Repair Proof Uploaded",
      desc: "Contractor uploaded after-repair evidence and material usage note.",
      actor: "Contractor",
      time: workOrder.afterRepairImageUrl ? "Recorded" : "Pending",
      badge: "Repair Uploaded",
      index: 4
    },
    {
      title: "AI Repair Verification Completed",
      desc: "Civica AI compared before/after evidence and generated repair confidence.",
      actor: "Civica AI",
      time: workOrder.verificationResult ? "Recorded" : "Pending",
      badge: "AI Verified",
      index: 5
    },
    {
      title: "Payment Recommendation Generated",
      desc: "Payment was recommended based on repair confidence, GPS verification, and evidence checks.",
      actor: "Civica Assurance Engine",
      time: workOrder.verificationResult ? "Recorded" : "Pending",
      badge: "Payment Recommended",
      index: 6
    },
    {
      title: "Payment Released",
      desc: "Admin approved verified contractor payout.",
      actor: "Municipal Admin",
      time: isPaymentReleased ? "Recorded" : "Pending",
      badge: "Payment Released",
      index: 7
    }
  ];

  return (
    <motion.div 
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      className="min-h-screen bg-[#FAFAFA] text-ink font-sans flex flex-col pb-12"
      style={{ backgroundImage: 'radial-gradient(#e5e7eb 1px, transparent 1px)', backgroundSize: '20px 20px' }}
    >
      {/* Top Navigation */}
      <header className="bg-white border-b border-slate-200 px-6 py-4 sticky top-0 z-50 shadow-sm flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4">
        <div className="flex items-center gap-4">
          <Link to="/dashboard" className="p-2 hover:bg-slate-100 rounded-full transition-colors text-muted hover:text-ink">
            <ArrowLeft size={20} />
          </Link>
          <div className="flex items-center gap-2 font-display font-bold text-xl text-ink">
            <span className="flex items-center justify-center w-7 h-7 rounded bg-ink text-white shadow-sm">
              <ShieldCheck size={16} />
            </span>
            Civica
          </div>
          <div className="h-5 w-px bg-slate-300 mx-2" />
          <span className="font-semibold text-slate-500 text-sm">Audit Trail</span>
        </div>
        
        <div className="flex items-center gap-3 w-full sm:w-auto">
          <button onClick={downloadReport} className="flex items-center gap-2 px-4 py-2 border border-slate-200 rounded-full text-sm font-bold text-slate-600 hover:bg-slate-50 transition-colors bg-white shadow-sm">
            <Download size={16} /> Download Report
          </button>
          <button onClick={copyCaseLink} className="flex items-center gap-2 px-4 py-2 border border-slate-200 rounded-full text-sm font-bold text-slate-600 hover:bg-slate-50 transition-colors bg-white shadow-sm">
            <Share2 size={16} /> Share Case
          </button>
          <Link to="/dashboard" className="flex items-center gap-2 px-4 py-2 bg-violet-deep text-white rounded-full text-sm font-bold shadow-md shadow-violet/20 hover:bg-violet transition-colors ml-2">
            Back to Dashboard
          </Link>
        </div>
      </header>

      <main className="max-w-[1600px] mx-auto p-4 md:p-6 flex-1 w-full flex flex-col gap-6 mt-4">
        
        <div className="mb-2">
          <h1 className="text-3xl font-display font-extrabold text-ink mb-1">Case Audit Trail</h1>
          <p className="text-sm text-slate-500 font-medium">Complete proof history for verified repair, contractor action, and payment release.</p>
        </div>

        <div className="grid lg:grid-cols-12 gap-6 items-start">
          
          {/* LEFT COLUMN: Case Summary Card */}
          <div className="lg:col-span-4 space-y-6">
            <div className="bento-card bg-white p-6 border border-slate-200 h-full flex flex-col">
              <div className="flex justify-between items-start mb-6 border-b border-slate-100 pb-4">
                <div>
                  <h2 className="text-sm font-bold uppercase tracking-wide text-slate-400 mb-1">Case Summary</h2>
                  <div className="text-xl font-extrabold text-ink">{workOrder.workOrderId}</div>
                  <div className="text-xs text-violet font-semibold">{issue.id}</div>
                </div>
                <div className="flex flex-col gap-2 items-end">
                  <span className={`px-3 py-1 rounded-full text-xs font-bold whitespace-nowrap
                    ${isPaymentReleased ? 'bg-mint/10 text-mint border border-mint/20' : 
                      workOrder.status === 'Rework Required' ? 'bg-coral/10 text-coral border border-coral/20' :
                      'bg-violet/10 text-violet border border-violet/20'}`}>
                    {workOrder.status}
                  </span>
                  {isAIVerified && (
                    <span className="px-2 py-0.5 rounded-full bg-mint/10 text-mint text-[10px] font-bold flex items-center gap-1">
                      <ShieldCheck size={10} /> AI Verified
                    </span>
                  )}
                </div>
              </div>

              <div className="space-y-4 mb-6">
                <div>
                  <div className="text-[10px] uppercase font-bold text-slate-400 mb-1">Issue</div>
                  <div className="text-sm font-bold text-ink">{issue.title}</div>
                </div>
                <div className="grid grid-cols-2 gap-4">
                  <div>
                    <div className="text-[10px] uppercase font-bold text-slate-400 mb-1">Category</div>
                    <div className="text-sm font-semibold text-slate-700">{issue.category}</div>
                  </div>
                  <div>
                    <div className="text-[10px] uppercase font-bold text-slate-400 mb-1">Severity</div>
                    <div className={`text-sm font-bold ${issue.severity === 'High' ? 'text-coral' : issue.severity === 'Medium' ? 'text-amber' : 'text-mint'}`}>{issue.severity}</div>
                  </div>
                </div>
                <div>
                  <div className="text-[10px] uppercase font-bold text-slate-400 mb-1">Location</div>
                  <div className="text-sm font-semibold text-slate-700 flex items-center gap-1"><MapPin size={14} className="text-slate-400"/> {issue.location}</div>
                </div>
                <div className="grid grid-cols-2 gap-4 border-t border-slate-100 pt-4">
                  <div>
                    <div className="text-[10px] uppercase font-bold text-slate-400 mb-1">Reported By</div>
                    <div className="text-sm font-semibold text-slate-700 flex items-center gap-1"><User size={14} className="text-slate-400"/> {issue.reportedBy}</div>
                  </div>
                  <div>
                    <div className="text-[10px] uppercase font-bold text-slate-400 mb-1">Created At</div>
                    <div className="text-sm font-semibold text-slate-700 flex items-center gap-1"><Clock size={14} className="text-slate-400"/> {issue.createdAt}</div>
                  </div>
                </div>
              </div>

              <div className="mt-auto">
                <div className="text-[10px] uppercase font-bold text-slate-400 mb-3">Evidence Records</div>
                <div className="grid grid-cols-2 gap-3">
                  <div className="space-y-1">
                    <div className="text-[10px] font-bold text-slate-500 text-center">Reported Evidence</div>
                    <div className="aspect-square bg-slate-100 rounded-lg border border-slate-200 relative overflow-hidden group">
                      {issue.beforeImageUrl ? (
                        <div className="absolute inset-0 bg-cover bg-center" style={{ backgroundImage: `url(${issue.beforeImageUrl})` }} />
                      ) : (
                        <div className="absolute inset-0 flex items-center justify-center text-slate-300"><ImageIcon size={24} /></div>
                      )}
                    </div>
                  </div>
                  <div className="space-y-1">
                    <div className="text-[10px] font-bold text-slate-500 text-center">Repair Proof</div>
                    <div className="aspect-square bg-slate-100 rounded-lg border border-slate-200 relative overflow-hidden group">
                      {workOrder.afterRepairImageUrl ? (
                        <div className="absolute inset-0 bg-cover bg-center" style={{ backgroundImage: `url(${workOrder.afterRepairImageUrl})` }} />
                      ) : (
                        <div className="absolute inset-0 flex flex-col items-center justify-center text-slate-400 p-2 text-center bg-slate-50">
                          <Camera size={20} className="mb-1 opacity-50" />
                          <span className="text-[9px] font-medium leading-tight">Repair proof not uploaded yet</span>
                        </div>
                      )}
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>

          {/* CENTER COLUMN: Audit Timeline */}
          <div className="lg:col-span-4 space-y-6">
            <div className="bento-card bg-white p-6 border border-slate-200 h-full">
              <h2 className="text-sm font-bold uppercase tracking-wide text-slate-400 mb-6 border-b border-slate-100 pb-4">Audit Timeline</h2>
              
              <div className="relative pl-6 space-y-6 before:absolute before:inset-y-2 before:left-[11px] before:w-[2px] before:bg-slate-100">
                {timelineSteps.map((step) => {
                  const status = getStepStatus(step.index);
                  
                  let dotColor = 'border-slate-200 text-slate-300 bg-white';
                  let innerDot = <div className="w-2 h-2 rounded-full bg-slate-200" />;
                  let textColor = 'text-slate-400';
                  let badgeClass = 'bg-slate-100 text-slate-500';

                  if (status === 'completed') {
                    dotColor = 'border-mint text-mint bg-white';
                    innerDot = <CheckCircle2 size={14} className="text-mint bg-white rounded-full" />;
                    textColor = 'text-ink';
                    badgeClass = 'bg-mint/10 text-mint';
                  } else if (status === 'current') {
                    dotColor = 'border-violet text-violet bg-white shadow-[0_0_0_4px_rgba(124,58,237,0.1)]';
                    innerDot = <div className="w-2 h-2 rounded-full bg-violet animate-pulse" />;
                    textColor = 'text-ink';
                    badgeClass = 'bg-violet/10 text-violet';
                  }

                  // Handle rework failure case on current step
                  if (status === 'current' && workOrder.status === 'Rework Required' && step.title === 'AI Repair Verification Completed') {
                    dotColor = 'border-coral text-coral bg-white';
                    innerDot = <AlertCircle size={14} className="text-coral bg-white rounded-full" />;
                    textColor = 'text-ink';
                    badgeClass = 'bg-coral/10 text-coral';
                  }

                  return (
                    <div key={step.index} className={`relative ${status === 'pending' ? 'opacity-50' : ''}`}>
                      <div className={`absolute -left-[31px] w-6 h-6 rounded-full border-2 flex items-center justify-center z-10 ${dotColor}`}>
                        {innerDot}
                      </div>
                      <div>
                        <div className="flex justify-between items-start mb-1">
                          <p className={`text-sm font-bold ${textColor}`}>{step.title}</p>
                          <span className={`text-[9px] font-bold px-2 py-0.5 rounded uppercase tracking-wider ${badgeClass}`}>{step.badge}</span>
                        </div>
                        <p className="text-xs text-slate-500 mb-2 leading-relaxed">{step.desc}</p>
                        <div className="flex items-center justify-between text-[10px] font-semibold text-slate-400">
                          <span className="flex items-center gap-1"><User size={10} /> {step.actor}</span>
                          <span className="flex items-center gap-1"><Clock size={10} /> {step.time}</span>
                        </div>
                      </div>
                    </div>
                  );
                })}
              </div>
            </div>
          </div>

          {/* RIGHT COLUMN: Verification & Payment Proof */}
          <div className="lg:col-span-4 space-y-4">
            
            {/* Card 1: AI Verification Summary */}
            <div className="bento-card bg-slate-900 text-white p-5 relative overflow-hidden shadow-lg shadow-violet/10">
              <div className="absolute top-0 right-0 w-32 h-32 bg-violet/20 rounded-full blur-2xl mix-blend-screen pointer-events-none" />
              <div className="flex items-center justify-between mb-4 relative z-10 border-b border-slate-700 pb-3">
                <h2 className="text-sm font-bold uppercase tracking-wide text-slate-300 flex items-center gap-2"><Activity size={16} className="text-violet"/> AI Verification Summary</h2>
              </div>
              
              {workOrder.verificationResult ? (
                <div className="relative z-10 space-y-3">
                  <div className="flex justify-between items-center bg-slate-800/50 p-3 rounded-lg border border-slate-700/50">
                    <div>
                      <div className="text-[10px] font-bold text-slate-400 uppercase tracking-wider mb-0.5">Repair Confidence</div>
                      <div className="text-xl font-extrabold text-mint flex items-center gap-1.5"><ShieldCheck size={16}/> {workOrder.verificationResult.repairConfidence}%</div>
                    </div>
                    <div className="text-right">
                      <div className="text-[10px] font-bold text-slate-400 uppercase tracking-wider mb-0.5">Location Match</div>
                      <div className="text-xl font-extrabold text-mint">{workOrder.verificationResult.sameLocationMatch}%</div>
                    </div>
                  </div>
                  
                  <div className="grid grid-cols-2 gap-2 text-xs">
                    <div className="bg-slate-800/30 p-2 rounded border border-slate-700/30 flex justify-between items-center">
                      <span className="text-slate-400 font-semibold">GPS Verified</span>
                      <span className={workOrder.verificationResult.gpsVerified ? 'text-mint font-bold' : 'text-slate-300'}>{workOrder.verificationResult.gpsVerified ? 'Yes' : 'No'}</span>
                    </div>
                    <div className="bg-slate-800/30 p-2 rounded border border-slate-700/30 flex justify-between items-center">
                      <span className="text-slate-400 font-semibold">Time Verified</span>
                      <span className={workOrder.verificationResult.timestampVerified ? 'text-mint font-bold' : 'text-slate-300'}>{workOrder.verificationResult.timestampVerified ? 'Yes' : 'No'}</span>
                    </div>
                    <div className="bg-slate-800/30 p-2 rounded border border-slate-700/30 flex justify-between items-center">
                      <span className="text-slate-400 font-semibold">Tamper Risk</span>
                      <span className={workOrder.verificationResult.evidenceTamperRisk === 'Low' ? 'text-mint font-bold' : 'text-amber font-bold'}>{workOrder.verificationResult.evidenceTamperRisk}</span>
                    </div>
                    <div className="bg-slate-800/30 p-2 rounded border border-slate-700/30 flex justify-between items-center">
                      <span className="text-slate-400 font-semibold">Issue Resolved</span>
                      <span className={workOrder.verificationResult.issueResolved ? 'text-mint font-bold' : 'text-coral font-bold'}>{workOrder.verificationResult.issueResolved ? 'Yes' : 'No'}</span>
                    </div>
                  </div>
                  
                  <div className={`mt-2 p-3 rounded-lg text-sm font-bold border ${workOrder.verificationResult.recommendation === 'Release Payment' ? 'bg-mint/10 text-mint border-mint/20' : 'bg-coral/10 text-coral border-coral/20'}`}>
                    Recommendation: {workOrder.verificationResult.recommendation}
                  </div>
                </div>
              ) : (
                <div className="relative z-10 py-6 text-center text-slate-400">
                  <Lock size={24} className="mx-auto mb-2 opacity-50" />
                  <p className="text-xs font-medium">AI repair verification has not been completed yet.</p>
                </div>
              )}
            </div>

            {/* Card 2: Payment Assurance Summary */}
            <div className="bento-card bg-white p-5 border border-slate-200 shadow-sm">
              <h2 className="text-sm font-bold uppercase tracking-wide text-slate-400 mb-4 border-b border-slate-100 pb-3 flex items-center gap-2"><Lock size={16} className="text-amber"/> Payment Assurance</h2>
              
              <div className="space-y-4">
                <div className="flex justify-between items-end">
                  <div>
                    <div className="text-[10px] font-bold text-slate-400 uppercase tracking-wider mb-1">Estimated Cost</div>
                    <div className="text-2xl font-extrabold text-ink">{workOrder.estimatedCost}</div>
                  </div>
                  <div className={`px-3 py-1 rounded text-xs font-bold ${isPaymentReleased ? 'bg-mint/10 text-mint' : 'bg-amber/10 text-amber'}`}>
                    {isPaymentReleased ? 'Released' : 'Pending Authorization'}
                  </div>
                </div>

                <div className="bg-slate-50 p-3 rounded-lg border border-slate-100 text-xs space-y-2">
                  <div className="flex justify-between">
                    <span className="font-semibold text-slate-500">Release Rule</span>
                    <span className="font-bold text-slate-700 text-right w-2/3">AI Confidence &gt; 80% + GPS verified + Admin approval</span>
                  </div>
                  <div className="flex justify-between pt-2 border-t border-slate-200">
                    <span className="font-semibold text-slate-500">Approval Status</span>
                    <span className={`font-bold ${isPaymentReleased ? 'text-mint' : 'text-slate-400'}`}>{isPaymentReleased ? 'Approved by Admin' : 'Awaiting Review'}</span>
                  </div>
                </div>
              </div>
            </div>

            {/* Card 3: Contractor Performance Snapshot */}
            <div className="bento-card bg-white p-5 border border-slate-200 shadow-sm">
              <h2 className="text-sm font-bold uppercase tracking-wide text-slate-400 mb-4 border-b border-slate-100 pb-3 flex items-center gap-2"><User size={16} className="text-blue-500"/> Contractor Record</h2>
              
              <div className="flex items-start gap-3 mb-4">
                <div className="w-10 h-10 rounded-full bg-slate-100 border border-slate-200 overflow-hidden flex-shrink-0">
                   <img src="https://images.unsplash.com/photo-1560250097-0b93528c311a?q=80&w=256&auto=format&fit=crop" alt="Contractor" className="w-full h-full object-cover" />
                </div>
                <div>
                  <div className="font-bold text-ink">{contractor.name}</div>
                  <div className="text-xs text-slate-500">{contractor.tier}</div>
                </div>
                <div className="ml-auto text-center">
                  <div className="text-lg font-extrabold text-ink leading-none mb-1">{contractor.contractorScore}</div>
                  <div className="text-[9px] font-bold text-slate-400 uppercase">Score</div>
                </div>
              </div>

              <div className="grid grid-cols-2 gap-2 text-xs">
                 <div className="bg-slate-50 p-2 rounded flex flex-col">
                   <span className="text-slate-400 font-semibold mb-1">SLA Compliance</span>
                   <span className="font-bold text-mint">{contractor.slaCompliance}</span>
                 </div>
                 <div className="bg-slate-50 p-2 rounded flex flex-col">
                   <span className="text-slate-400 font-semibold mb-1">Rework Rate</span>
                   <span className="font-bold text-ink">{contractor.repeatFailureRate}</span>
                 </div>
                 <div className="bg-slate-50 p-2 rounded flex flex-col col-span-2">
                   <span className="text-slate-400 font-semibold mb-1">Average Repair Time</span>
                   <span className="font-bold text-ink">{contractor.averageRepairTime}</span>
                 </div>
              </div>
            </div>

          </div>
        </div>

        {/* BOTTOM SECTION: Evidence Vault */}
        <div className="mt-4 bento-card bg-white p-6 border border-slate-200">
          <h2 className="text-sm font-bold uppercase tracking-wide text-slate-400 mb-4 flex items-center gap-2"><FileText size={16}/> Evidence Vault</h2>
          
          <div className="grid grid-cols-2 md:grid-cols-5 gap-4">
            
            <div className="border border-slate-200 rounded-xl p-3 flex flex-col justify-between group hover:border-violet transition-colors">
              <div className="mb-3 flex justify-between items-start">
                <ImageIcon size={20} className="text-slate-400 group-hover:text-violet transition-colors" />
                <span className="text-[9px] font-bold uppercase px-1.5 py-0.5 rounded bg-slate-100 text-slate-500">Stored</span>
              </div>
              <div>
                <div className="text-xs font-bold text-ink mb-0.5">Original Evidence</div>
                <div className="text-[10px] text-slate-500">Source: Citizen App</div>
              </div>
            </div>

            <div className={`border border-slate-200 rounded-xl p-3 flex flex-col justify-between group hover:border-violet transition-colors ${!workOrder.afterRepairImageUrl ? 'opacity-50 grayscale' : ''}`}>
              <div className="mb-3 flex justify-between items-start">
                <Camera size={20} className="text-slate-400 group-hover:text-violet transition-colors" />
                <span className={`text-[9px] font-bold uppercase px-1.5 py-0.5 rounded ${workOrder.afterRepairImageUrl ? 'bg-mint/10 text-mint' : 'bg-slate-100 text-slate-500'}`}>
                  {workOrder.afterRepairImageUrl ? 'Verified' : 'Pending'}
                </span>
              </div>
              <div>
                <div className="text-xs font-bold text-ink mb-0.5">Repair Proof</div>
                <div className="text-[10px] text-slate-500">Source: {contractor.name}</div>
              </div>
            </div>

            <div className="border border-slate-200 rounded-xl p-3 flex flex-col justify-between group hover:border-violet transition-colors">
              <div className="mb-3 flex justify-between items-start">
                <Activity size={20} className="text-slate-400 group-hover:text-violet transition-colors" />
                <span className="text-[9px] font-bold uppercase px-1.5 py-0.5 rounded bg-blue-500/10 text-blue-500">Generated</span>
              </div>
              <div>
                <div className="text-xs font-bold text-ink mb-0.5">AI Issue DNA</div>
                <div className="text-[10px] text-slate-500">Source: Civica AI</div>
              </div>
            </div>

            <div className={`border border-slate-200 rounded-xl p-3 flex flex-col justify-between group hover:border-violet transition-colors ${!workOrder.verificationResult ? 'opacity-50 grayscale' : ''}`}>
              <div className="mb-3 flex justify-between items-start">
                <ShieldCheck size={20} className="text-slate-400 group-hover:text-violet transition-colors" />
                <span className={`text-[9px] font-bold uppercase px-1.5 py-0.5 rounded ${workOrder.verificationResult ? 'bg-mint/10 text-mint' : 'bg-slate-100 text-slate-500'}`}>
                  {workOrder.verificationResult ? 'Recorded' : 'Pending'}
                </span>
              </div>
              <div>
                <div className="text-xs font-bold text-ink mb-0.5">AI Verification</div>
                <div className="text-[10px] text-slate-500">Source: Civica AI</div>
              </div>
            </div>

            <div className={`border border-slate-200 rounded-xl p-3 flex flex-col justify-between group hover:border-violet transition-colors ${!isPaymentReleased ? 'opacity-50 grayscale' : ''}`}>
              <div className="mb-3 flex justify-between items-start">
                <Lock size={20} className="text-slate-400 group-hover:text-violet transition-colors" />
                <span className={`text-[9px] font-bold uppercase px-1.5 py-0.5 rounded ${isPaymentReleased ? 'bg-mint/10 text-mint' : 'bg-amber/10 text-amber'}`}>
                  {isPaymentReleased ? 'Released' : 'Locked'}
                </span>
              </div>
              <div>
                <div className="text-xs font-bold text-ink mb-0.5">Payment Approval</div>
                <div className="text-[10px] text-slate-500">Source: Municipal Admin</div>
              </div>
            </div>

          </div>
        </div>

      </main>
    </motion.div>
  );
}
